version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=the_game
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # This will run the init script on first startup
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  redis_data:
  postgres_data:
