version: "3.8"

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=the_game
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # This will run the init script on first startup
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  the-game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: "postgres://user:password@postgres:5432/the_game?sslmode=disable"
      REDIS_URL: "redis://redis:6379"

volumes:
  redis_data:
  postgres_data:
