version: "3.9"

x-bot-base: &bot-base
  build:
    context: .
    dockerfile: Dockerfile
    target: bot-image
  depends_on:
    - the-game-server
  volumes:
    - ./logs:/app/logs

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=the_game
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # This will run the init script on first startup
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  the-game-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server-image
    ports:
      - "50051:50051"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_URL: "postgres://user:password@postgres:5432/the_game?sslmode=disable"
      REDIS_URL: "redis://redis:6379"

  bot:
    <<: *bot-base
    command:
      [
        "--server=the-game-server:50051",
        "--strategy=random",
        "--num_games=1667",
      ]
    deploy:
      replicas: 2

  bot-minimal-jump:
    <<: *bot-base
    command:
      [
        "--server=the-game-server:50051",
        "--strategy=minimal-jump",
        "--num_games=1667",
      ]
    deploy:
      replicas: 2

  bot-safe-ten:
    <<: *bot-base
    command:
      [
        "--server=the-game-server:50051",
        "--strategy=safe-ten",
        "--num_games=1667",
      ]
    deploy:
      replicas: 2

volumes:
  redis_data:
  postgres_data:
